### ISSUE TITLE
没给数据库数据，

### ISSUE THREAD

**Issue by kedongyu** [YuJian95/hospital-service#1]
，，，，，，

**Comment by xdmdcp** [comment]
详情请看[部署步骤](https://github.com/YuJian95/hospital-service#%E9%83%A8%E7%BD%B2%E6%AD%A5%E9%AA%A4)
数据表设计，可能还会变动。因为系统还没做完，预计四月底会结束。

**Comment by xdmdcp** [comment]
@kedongyu 如对你有所帮助，麻烦请 star、 watch、 fork，一键三连支持一下！
