### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by adminlove520** [YuJian95/hospital-service#2]
部署的时候出现“Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.”的错误，请问怎么解决呀

**Comment by ghost** [comment]
导入hosptial.sql时，数据库无数据，因此找不到用户名，后端应该是正常的。是不是初始化数据表有问题，log也没打印出生成表的信息

**Comment by ghost** [comment]
Could not validate configuration attributes as the SecurityMetadataSource did not return any attributes from getAllConfigAttributes() 
您看下这条信息

**Comment by xdmdcp** [comment]
> 部署的时候出现“Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.”的错误，请问怎么解决呀

这个问题把application-dev.yml重命名为application.yml即可。

**Comment by adminlove520** [comment]
> > 部署的时候出现“Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.”的错误，请问怎么解决呀
> 
> 这个问题把application-dev.yml重命名为application.yml即可。

**Comment by xdmdcp** [comment]
> 导入hosptial.sql时，数据库无数据，因此找不到用户名，后端应该是正常的。是不是初始化数据表有问题，log也没打印出生成表的信息

数据库脚本暂时**只有数据表结构**，**数据记录晚点更新一下**。

**Comment by ghost** [comment]
但是数据库还是没数据  admin登录不了的；小程序api能访问到，其余部分还没来得及测

**Comment by xdmdcp** [comment]
> Could not validate configuration attributes as the SecurityMetadataSource did not return any attributes from getAllConfigAttributes()
> 您看下这条信息

这个是正常情况，因为权限那块是根据url动态鉴权，但是读取数据库的权限信息时，出现异常，**我也还没解决。但是不影响使用**，系统会过滤点没有jwt的请求，放开请求的url在application.yml中配置即可。

**Comment by ghost** [comment]
那admin登录不了这是什么原因呢 提示 用户不存在

**Comment by ghost** [comment]
{"result":{"code":404,"message":"不存在，该账号名称！"},"basePath":"http://localhost:8080","method":"GET","ip":"0:0:0:0:0:0:0:1","parameter":[{"name":"admin"},

**Comment by ghost** [comment]
关键前端也没发现写死的登录数据，应该是在数据库呢，但是数据库整个就是空的

**Comment by ghost** [comment]
方便加个q嘛  791751568

**Comment by xdmdcp** [comment]
> 关键前端也没发现写死的登录数据，应该是在数据库呢，但是数据库整个就是空的

查看最新的commit，更新了数据库脚本，你也**可以直接复制执行，最下方的插入数据操作部分代码**。

**Comment by ghost** [comment]
好的

**Comment by xdmdcp** [comment]
> 好的

如对你有所帮助，麻烦请 star、 watch、 fork，一键三连支持一下！
**如需讨论或帮助可加Q群：866724245。**
