### ISSUE TITLE
这个前端代码和小程序是怎么部署的？

### ISSUE THREAD

**Issue by TTC520** [YuJian95/hospital-service#4]
这个没有前端的吗？
只有接口文档页面？

**Comment by wz-make** [comment]
我没看过这个项目，也只是收藏一下而已，不好意义



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuJian95/hospital"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月5日(星期三) 下午2:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[YuJian95/hospital] 这个怎么进去医院系统，小程序怎么部署 (#4)





 
这个没有前端的吗？
 只有接口文档页面？

**Comment by ITdakaWGY** [comment]
同问，小程序端导入进微信开发者工具时报错

**Comment by xdmdcp** [comment]
> 同问，小程序端导入进微信开发者工具时报错

@ITdakaWGY 

小程序通过 [hbuilder](https://www.dcloud.io/) 导入项目运行。

**Comment by xdmdcp** [comment]
> > 同问，小程序端导入进微信开发者工具时报错
> 
> @ITdakaWGY
> 
> 小程序通过 [hbuilder](https://www.dcloud.io/) 导入项目运行。

@TTC520 具体部署步骤请看相应项目 readme 说明。

**Comment by lunarmare** [comment]
使用WeChat导入并且运行小程序




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuJian95/hospital"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 晚上9:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [YuJian95/hospital] 这个前端代码和小程序是怎么部署的？ (#4)





   
同问，小程序端导入进微信开发者工具时报错
  
@ITdakaWGY
 
小程序通过 hbuilder 导入项目运行。
  
@TTC520 具体部署步骤请看相应项目 readme 说明。
