### ISSUE TITLE
运行不起来，报错

### ISSUE THREAD

**Issue by rooteelee** [YuJian95/hospital-service#6]
Name [cn.yujian95.hospital.common.security.JwtAuthenticationTokenFilter/userDetailsService] is not bound in this Context. Unable to find [cn.yujian95.hospital.common.security.JwtAuthenticationTokenFilter].

**Comment by xdmdcp** [comment]
没有详细的信息暂时无法判断原因，我自己启动时没有问题的。

**Comment by kedongyu** [comment]
祝 身体健康，工作顺利！
